name: Get Unity License

on:
  workflow_dispatch:

jobs:
  getlicense:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get Unity license
        uses: game-ci/unity-request-activation-file@v2
        id: getManualLicenseFile
        with:
          unityVersion: 6000.2.13f1

      - name: Upload .alf file
        uses: actions/upload-artifact@v4
        with:
          name: manual-license-file
          path: ${{ steps.getManualLicenseFile.outputs.filePath }}